name: festim-hyperion

channels:
  - conda-forge

dependencies:
  # - festim
  - fenics-dolfinx
  - scifem
  - python-gmsh
  - pyvista
  - pip
  - pip:
      - git+https://github.com/festim-dev/FESTIM@fix-penalty